// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBifkoBCpiVciZdyUk7lBMuo7qyPTssPPU',
    appId: '1:786929404346:web:9acd3d516aa1751c0ff583',
    messagingSenderId: '786929404346',
    projectId: 'event-app-c7dca',
    authDomain: 'event-app-c7dca.firebaseapp.com',
    storageBucket: 'event-app-c7dca.firebasestorage.app',
    measurementId: 'G-YZPHYC1P6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCamAeatRm-1Do8z9s59dQkMtg_uyHTsyk',
    appId: '1:786929404346:android:eebfcf7c377d8d280ff583',
    messagingSenderId: '786929404346',
    projectId: 'event-app-c7dca',
    storageBucket: 'event-app-c7dca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZUPltRHC1KyxHWtkyEjlUN20BDbNGU9M',
    appId: '1:786929404346:ios:e7e57aa1ba6f674b0ff583',
    messagingSenderId: '786929404346',
    projectId: 'event-app-c7dca',
    storageBucket: 'event-app-c7dca.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZUPltRHC1KyxHWtkyEjlUN20BDbNGU9M',
    appId: '1:786929404346:ios:e7e57aa1ba6f674b0ff583',
    messagingSenderId: '786929404346',
    projectId: 'event-app-c7dca',
    storageBucket: 'event-app-c7dca.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBifkoBCpiVciZdyUk7lBMuo7qyPTssPPU',
    appId: '1:786929404346:web:730a0fd72f08c3250ff583',
    messagingSenderId: '786929404346',
    projectId: 'event-app-c7dca',
    authDomain: 'event-app-c7dca.firebaseapp.com',
    storageBucket: 'event-app-c7dca.firebasestorage.app',
    measurementId: 'G-9MKD0K9EC1',
  );

}